prd:
  catalog_name: prod
  schema_name: price_optimisation
test:
  catalog_name: acc
  schema_name: price_optimisation
dev:
  catalog_name: dev
  schema_name: price_optimisation


experiment_name_basic: /Shared/product-price-optimisation-basic
experiment_name_custom: /Shared/product-price-optimisation-custom

parameters:
  num_days_train: 730
  num_items_subset: 10
  num_stores_subset: 10
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6
  testing: true


num_features:
  - wday
  - month
  - year
  - dayofweek
  - dayofyear
  - week
  - days_since_first_sale
  - lag_t7
  - rolling_mean_lag7_w7
  - lag_t28
  - rolling_mean_lag28_w7
  - item_running_avg
  - store_running_avg

cat_features:
  - snap_CA
  - snap_TX
  - snap_WI
  - is_event


target: demand
